// web-apps/portfolio-blog/nextjs-portfolio/components/Footer.tsx
import { FaGithub, FaLinkedin, FaTwitter, FaEnvelope } from 'react-icons/fa'

export default function Footer() {
  const currentYear = new Date().getFullYear()

  return (
    <footer className="bg-gray-900 text-white py-12">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          {/* About */}
          <div>
            <h3 className="text-xl font-bold mb-4">Portfolio</h3>
            <p className="text-gray-400">
              全端工程師，專注於打造優質的網頁應用。使用現代化技術棧，結合 AI 工具提升開發效率。
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h3 className="text-xl font-bold mb-4">快速連結</h3>
            <ul className="space-y-2">
              <li>
                <a href="/projects" className="text-gray-400 hover:text-primary-400 transition-colors">
                  作品集
                </a>
              </li>
              <li>
                <a href="/blog" className="text-gray-400 hover:text-primary-400 transition-colors">
                  部落格
                </a>
              </li>
              <li>
                <a href="/about" className="text-gray-400 hover:text-primary-400 transition-colors">
                  關於我
                </a>
              </li>
              <li>
                <a href="/contact" className="text-gray-400 hover:text-primary-400 transition-colors">
                  聯絡我
                </a>
              </li>
            </ul>
          </div>

          {/* Social */}
          <div>
            <h3 className="text-xl font-bold mb-4">聯絡方式</h3>
            <div className="flex space-x-4">
              <a
                href="https://github.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-400 hover:text-primary-400 transition-colors"
              >
                <FaGithub size={24} />
              </a>
              <a
                href="https://linkedin.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-400 hover:text-primary-400 transition-colors"
              >
                <FaLinkedin size={24} />
              </a>
              <a
                href="https://twitter.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-400 hover:text-primary-400 transition-colors"
              >
                <FaTwitter size={24} />
              </a>
              <a
                href="mailto:your.email@example.com"
                className="text-gray-400 hover:text-primary-400 transition-colors"
              >
                <FaEnvelope size={24} />
              </a>
            </div>
          </div>
        </div>

        <div className="border-t border-gray-800 pt-8 text-center text-gray-400">
          <p>&copy; {currentYear} Portfolio. All rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}

// web-apps/portfolio-blog/nuxt-portfolio/components/Footer.vue
<template>
  <footer class="bg-gray-900 text-white py-12 mt-20">
    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
        <!-- About -->
        <div>
          <h3 class="text-xl font-bold mb-4">Portfolio</h3>
          <p class="text-gray-400">
            全端工程師，專注於使用 Vue 與 Nuxt 打造現代化網頁應用。
          </p>
        </div>

        <!-- Quick Links -->
        <div>
          <h3 class="text-xl font-bold mb-4">快速連結</h3>
          <ul class="space-y-2">
            <li v-for="link in links" :key="link.href">
              <NuxtLink
                :to="link.href"
                class="text-gray-400 hover:text-primary-400 transition-colors"
              >
                {{ link.name }}
              </NuxtLink>
            </li>
          </ul>
        </div>

        <!-- Social -->
        <div>
          <h3 class="text-xl font-bold mb-4">社群連結</h3>
          <div class="flex space-x-4">
            <a
              v-for="social in socials"
              :key="social.name"
              :href="social.href"
              target="_blank"
              rel="noopener noreferrer"
              class="text-gray-400 hover:text-primary-400 transition-colors"
            >
              <Icon :name="social.icon" class="w-6 h-6" />
            </a>
          </div>
        </div>
      </div>

      <div class="border-t border-gray-800 pt-8 text-center text-gray-400">
        <p>&copy; {{ currentYear }} Portfolio. All rights reserved.</p>
        <p class="mt-2">Built with Nuxt 3 + Vue 3 + Tailwind CSS</p>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
const currentYear = new Date().getFullYear()

const links = [
  { name: '作品集', href: '/projects' },
  { name: '部落格', href: '/blog' },
  { name: '關於我', href: '/about' },
  { name: '聯絡我', href: '/contact' },
]

const socials = [
  { name: 'GitHub', icon: 'mdi:github', href: 'https://github.com' },
  { name: 'LinkedIn', icon: 'mdi:linkedin', href: 'https://linkedin.com' },
  { name: 'Twitter', icon: 'mdi:twitter', href: 'https://twitter.com' },
]
</script>
