// web-apps/portfolio-blog/nuxt-portfolio/components/Header.vue
<template>
  <header class="sticky top-0 z-50 bg-white dark:bg-gray-800 shadow-sm">
    <nav class="container mx-auto px-4 py-4">
      <div class="flex justify-between items-center">
        <NuxtLink to="/" class="text-2xl font-bold text-primary-600">
          Portfolio
        </NuxtLink>

        <!-- Desktop Navigation -->
        <div class="hidden md:flex space-x-8">
          <NuxtLink
            v-for="item in navigation"
            :key="item.name"
            :to="item.href"
            class="text-gray-700 dark:text-gray-300 hover:text-primary-600 dark:hover:text-primary-400 transition-colors"
          >
            {{ item.name }}
          </NuxtLink>
        </div>

        <!-- Mobile Menu Button -->
        <button
          @click="mobileMenuOpen = !mobileMenuOpen"
          class="md:hidden text-gray-700 dark:text-gray-300"
        >
          <Icon :name="mobileMenuOpen ? 'heroicons:x-mark' : 'heroicons:bars-3'" class="w-6 h-6" />
        </button>
      </div>

      <!-- Mobile Navigation -->
      <div v-if="mobileMenuOpen" class="md:hidden mt-4 pb-4">
        <NuxtLink
          v-for="item in navigation"
          :key="item.name"
          :to="item.href"
          class="block py-2 text-gray-700 dark:text-gray-300 hover:text-primary-600 dark:hover:text-primary-400 transition-colors"
          @click="mobileMenuOpen = false"
        >
          {{ item.name }}
        </NuxtLink>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const navigation = [
  { name: '首頁', href: '/' },
  { name: '作品集', href: '/projects' },
  { name: '部落格', href: '/blog' },
  { name: '關於我', href: '/about' },
  { name: '聯絡', href: '/contact' },
]

const mobileMenuOpen = ref(false)
</script>

// web-apps/e-commerce/next-shop/components/Header.tsx
'use client'

import Link from 'next/link'
import { FiShoppingCart, FiMenu } from 'react-icons/fi'
import { useCartStore } from '@/store/cartStore'
import { useState } from 'react'

export default function Header() {
  const items = useCartStore((state) => state.items)
  const [isMenuOpen, setIsMenuOpen] = useState(false)

  const totalItems = items.reduce((sum, item) => sum + item.quantity, 0)

  return (
    <header className="bg-white shadow-md sticky top-0 z-50">
      <nav className="container mx-auto px-4 py-4">
        <div className="flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold text-primary-600">
            Next Shop
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-8">
            <Link href="/" className="hover:text-primary-600 transition-colors">
              首頁
            </Link>
            <Link href="/products" className="hover:text-primary-600 transition-colors">
              商品
            </Link>
            <Link href="/cart" className="relative hover:text-primary-600 transition-colors">
              <FiShoppingCart className="w-6 h-6" />
              {totalItems > 0 && (
                <span className="absolute -top-2 -right-2 bg-primary-600 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center">
                  {totalItems}
                </span>
              )}
            </Link>
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="md:hidden p-2"
          >
            <FiMenu className="w-6 h-6" />
          </button>
        </div>

        {/* Mobile Navigation */}
        {isMenuOpen && (
          <div className="md:hidden mt-4 space-y-3">
            <Link
              href="/"
              className="block py-2 hover:text-primary-600 transition-colors"
              onClick={() => setIsMenuOpen(false)}
            >
              首頁
            </Link>
            <Link
              href="/products"
              className="block py-2 hover:text-primary-600 transition-colors"
              onClick={() => setIsMenuOpen(false)}
            >
              商品
            </Link>
            <Link
              href="/cart"
              className="block py-2 hover:text-primary-600 transition-colors"
              onClick={() => setIsMenuOpen(false)}
            >
              購物車 ({totalItems})
            </Link>
          </div>
        )}
      </nav>
    </header>
  )
}
